In [2]:
import numpy as np
from numba import jit

In [59]:
@jit
def roll_axis(a: np.ndarray, shift: int, axis: int) -> np.ndarray:
    dim = a.ndim
    assert 0 <= axis < dim, f"axis {axis} for array with dimension {dim}"
    L = a.shape[axis]
    shift %= L
    if shift == 0:
        return a
    b = np.empty_like(a)
    # Code goes here
    if axis == 0:
        b[:shift, ...] = a[-shift:, ...]
        b[shift:, ...] = a[:-shift, ...]
    elif axis == dim - 1:
        b[..., :shift] = a[..., -shift:]
        b[..., shift:] = a[..., :-shift]
    else:
        prefix = (slice(None),) * axis
        # suffix = (slice(None),) * (dim - axis - 1)
        suffix = (Ellipsis,)
        b[prefix + (slice(None, shift),) + suffix] = a[prefix + (slice(-shift, None),) + suffix]
        b[prefix + (slice(shift, None),) + suffix] = a[prefix + (slice(None, -shift),) + suffix]
    return b

In [60]:
myarray = np.arange(24).reshape(2, 3, 4)
print(myarray)
print(roll_axis(myarray, 2, 0))

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


TypingError: Failed in nopython mode pipeline (step: nopython frontend)
No implementation of function Function(<built-in function mul>) found for signature:
 
 >>> mul(UniTuple(slice<a:b> x 1), int64)
 
There are 14 candidate implementations:
      - Of which 12 did not match due to:
      Overload of function 'mul': File: <numerous>: Line N/A.
        With argument(s): '(UniTuple(slice<a:b> x 1), int64)':
       No match.
      - Of which 2 did not match due to:
      Operator Overload in function 'mul': File: unknown: Line unknown.
        With argument(s): '(UniTuple(slice<a:b> x 1), int64)':
       No match for registered cases:
        * (int64, int64) -> int64
        * (int64, uint64) -> int64
        * (uint64, int64) -> int64
        * (uint64, uint64) -> uint64
        * (float32, float32) -> float32
        * (float64, float64) -> float64
        * (complex64, complex64) -> complex64
        * (complex128, complex128) -> complex128

During: typing of intrinsic-call at C:\Users\danie\AppData\Local\Temp\ipykernel_31612\3934560876.py (18)

File "..\..\..\AppData\Local\Temp\ipykernel_31612\3934560876.py", line 18:
<source missing, REPL/exec in use?>


In [38]:
myslice = slice(-1,None)
myarray = np.arange(10)

In [41]:
myarray.reshape(2,5)[(myslice, myslice)]

array([[9]])

In [39]:
myarray[myslice]

array([9])

In [24]:
@jit
def roll(a: np.ndarray, shift: tuple[int, ...]) -> np.ndarray:
    """
    Rolls the elements of an array. For 1D arrays, use np.roll.

    Parameters:
    a (np.ndarray): The input array.
    shift (tuple): The number of places by which elements are shifted. Must have the same length as the number of dimensions of a.

    Returns:
    np.ndarray: The rolled array.
    """
    dim = len(a.shape)
    assert len(shift) == dim, "The length of shift must be the same as the number of dimensions of a."

    b = a.copy()

    for i in range(dim):
        b = np.empty_like(a)

In [25]:
myarray = np.zeros((2, 2, 2, 2))
roll(myarray, (1, 0, 0, 0))

TypingError: Failed in nopython mode pipeline (step: nopython frontend)
No implementation of function Function(<class 'zip'>) found for signature:
 
 >>> zip(int64, int64)
 
There are 2 candidate implementations:
  - Of which 2 did not match due to:
  Overload of function 'zip': File: numba\core\typing\builtins.py: Line 1067.
    With argument(s): '(int64, int64)':
   No match.

During: resolving callee type: Function(<class 'zip'>)
During: typing of call at C:\Users\danie\AppData\Local\Temp\ipykernel_31612\975340562.py (4)


File "..\..\..\AppData\Local\Temp\ipykernel_31612\975340562.py", line 4:
<source missing, REPL/exec in use?>
