In [1]:
import numpy as np
from glob import glob
from datetime import datetime

In [13]:
fn = {}
for f in glob("slurm-*.out"):
    fn[int(f.split("_")[1].split(".")[0])] = f

In [14]:
lengths = []
for n in range(1000):
    with open(fn[n], "r") as f:
        lines = f.readlines()
        line = lines[0]
        if len(line) < 8:
            lengths.append(int(line))
        else:
            lengths.append(np.NaN)
            print(f"Failed to read {fn[n]}")

Failed to read slurm-51233247_691.out
Failed to read slurm-51233247_819.out
Failed to read slurm-51233247_820.out
Failed to read slurm-51233247_919.out
Failed to read slurm-51233247_920.out
Failed to read slurm-51233247_921.out
Failed to read slurm-51233247_922.out
Failed to read slurm-51233247_923.out
Failed to read slurm-51233247_924.out
Failed to read slurm-51233247_925.out
Failed to read slurm-51233247_962.out
Failed to read slurm-51233247_965.out
Failed to read slurm-51233247_968.out
Failed to read slurm-51233247_971.out
Failed to read slurm-51233247_972.out
Failed to read slurm-51233247_973.out
Failed to read slurm-51233247_974.out
Failed to read slurm-51233247_975.out
Failed to read slurm-51233247_999.out


In [15]:
lengths = np.array(lengths)

In [17]:
lengths = lengths.reshape((10, 100))

In [18]:
means = np.nanmean(lengths, axis=1)
stds = np.nanstd(lengths, axis=1)

In [23]:
f_means = np.array([means//3600, means%3600//60, np.round(means%60)])
f_stds = np.array([stds//3600, stds%3600//60, np.round(stds%60)])

In [24]:
print(f_means)
print(f_stds)

[[ 0.  0.  0.  0.  0.  0.  0.  0.  1.  1.]
 [ 2.  4.  6.  7. 14. 18. 27. 48.  4. 19.]
 [40. 55. 59.  5. 34. 58.  3.  4. 33. 50.]]
[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 1.  2.  2.  2.  5.  6.  7. 13. 18. 16.]
 [40. 41. 33. 22. 25. 13.  9. 26. 18.  3.]]
