In [1]:
import numpy as np
from glob import glob
from datetime import datetime

In [2]:
fn = {}
for f in glob("slurm-*.out"):
    fn[int(f.split("_")[1].split(".")[0])] = f

In [3]:
lengths = []
for n in range(1000):
    with open(fn[n], "r") as f:
        lines = f.readlines()
        line = lines[0]
        if len(line) < 8:
            lengths.append(int(line))
        else:
            lengths.append(np.NaN)
            print(f"Failed to read {fn[n]}")

Failed to read slurm-51250274_715.out
Failed to read slurm-51250274_725.out
Failed to read slurm-51250274_896.out
Failed to read slurm-51250274_898.out
Failed to read slurm-51250274_944.out


In [4]:
lengths = np.array(lengths)

In [14]:
lengths = lengths.reshape((5, 20, 10))

In [15]:
means = np.nanmean(lengths, axis=(1,2))
stds = np.nanstd(lengths, axis=(1,2))

In [16]:
f_means = np.array([means//3600, means%3600//60, np.round(means%60)])
f_stds = np.array([stds//3600, stds%3600//60, np.round(stds%60)])

In [17]:
print(f_means)
print(f_stds)

[[ 0.  0.  0.  0.  1.]
 [ 6. 10. 18. 46. 23.]
 [ 6. 49. 55. 53. 14.]]
[[ 0.  0.  0.  0.  0.]
 [ 3.  3.  5. 16. 20.]
 [21. 37. 21. 29. 52.]]
